# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

def soma(arg1, arg2):
    soma = arg1 + arg2
    return soma


def mult(arg1,arg2):
  mult = arg1 * arg2
  return mult


def divisao(arg1,arg2):
  divi = arg1 / arg2
  return divi

def subtracao(arg1,arg2):
  sub = arg1 - arg2
  return sub

print("\t---------------BEM VINDO A CALCULADORA PYTHON---------------")

print("\nSelecione uma opção para continuar\n")

print("1 - Soma\n2 - Multiplicação\n3 - subtração\n4 - Divisão")

print("\nDigite sua opção: (1/2/3/4)")

resposta = int(input())


while(resposta!= 0):

  if resposta == 1:
    num1 = int(input("\nDigite dois números que deseja somar\n ")) 
    num2 = int(input())
    print("A soma dos números é:", soma(num1,num2))
    
    print("\nDigite 0 para sair ou:")
    print("1 - Soma\n2 - Multiplicação\n3 - Subtração\n4 - Divisão")
    resposta = int(input())

  elif resposta == 2:
    
    num1 = int (input("\nDigite dois números que deseja multiplicar\n "))
    num2 = int(input())
    print("O produto dos valores é:", mult(num1,num2))  

    print("\nDigite 0 para sair ou:")
    print("1 - Soma\n2 - Multiplicação\n3 - Subtração\n4 - Divisão")
    resposta = int(input())

  elif resposta == 3:
    
    num1 = int (input("\nDigite um numero\n"))
    num2 = int(input("Qual numero deseja subtrair?"))
    print("Seu resultado é:",subtracao(num1,num2))

    print("\nDigite 0 para sair ou:")
    print("1 - Soma\n2 - Multiplicação\n3 - Subtração\n4 - Divisão")
    resposta = int(input())

  elif resposta == 4:
    
    num1 = int(input("\nDigite um numero:\n "))
    num2 = int(input("Por qual numero deseja dividir ? "))
    print("Seu resultado é:", divisao(num1,num2))  
   
    print("\nDigite 0 para sair ou:")
    print("1 - Soma\n2 - Multiplicação\n3 - Subtração\n4 - Divisão")
    resposta = int(input())